import { test, expect } from '@playwright/test';
import { seedFeed } from './fixtures';
import { exploreCircle } from './map-interaction';
test.beforeEach(async ({page,request}) => { await seedFeed(page,request); });
test('real discovery → save → explore → path → library → reopen', async ({ page, isMobile }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/scroll');
  const first = page.locator('.feed-slide').first();
  await expect(first.getByRole('heading', { name: 'Bioluminescence', exact: true })).toBeVisible({ timeout: 30000 });
  await expect.poll(() => first.locator('.post-media').evaluate((img: HTMLImageElement) => img.naturalWidth), { timeout: 20000 }).toBeGreaterThan(0);
  await first.getByRole('button', { name: 'Enlarge image of Bioluminescence' }).click();
  await expect(first.locator('dialog')).toBeVisible();
  await first.getByRole('button', { name: 'Close image' }).click();
  await first.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(first.getByRole('button', { name: 'Saved', exact: true })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0,0));
  await page.screenshot({ path: `test-results/${info.project.name}-scroll.png`, fullPage: false });
  await first.getByRole('link', { name: 'Explore topic' }).click();
  await expect(page.locator('.center-node strong')).toHaveText('Bioluminescence', { timeout: 30000 });
  // Source connections and later Gemini organization accumulate in the map.
  await expect.poll(()=>page.locator('.topic-node').count()).toBeGreaterThanOrEqual(7);
  await expect(page.getByRole('tabpanel')).toContainText('Bioluminescence');
  await page.screenshot({ path: `test-results/${info.project.name}-explore.png`, fullPage: false });
  const relatedTitle = await page.locator('.related-accessible button').first().innerText();
  await exploreCircle(page.getByRole('button', { name: `Explore connections for ${relatedTitle}`, exact: true }),isMobile);
  await expect(page.locator('.center-node strong')).toHaveText(relatedTitle, { timeout: 30000 });
  await expect(page.getByRole('button', { name: 'Save path', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Save path', exact: true }).click();
  await page.getByRole('navigation').getByRole('link', { name: /Library/ }).click();
  await expect(page.locator('.library-list .saved-topic h2').first()).toHaveText('Bioluminescence');
  await expect(page.locator('.path-card')).toHaveCount(1);
  await page.reload();
  await expect(page.locator('.library-list .saved-topic h2').first()).toHaveText('Bioluminescence');
  await page.screenshot({ path: `test-results/${info.project.name}-library.png`, fullPage: false });
  await page.getByRole('link', { name: 'Reopen 2-topic path' }).click();
  await expect(page.locator('.center-node strong')).toHaveText(relatedTitle, { timeout: 30000 });
  await expect(page.locator('.explore-trail')).toContainText('Bioluminescence');
  await page.reload();
  await expect(page.locator('.center-node strong')).toHaveText(relatedTitle, { timeout: 30000 });
  await expect(page.locator('.explore-trail')).toContainText('Bioluminescence');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
test('feed failures offer a working retry', async ({ page }) => {
  let fail = true;
  await page.route('**/api/wikipedia?offset=*', async route => { if (fail) await route.fulfill({ status: 502, contentType: 'application/json', body: '{"error":"Unavailable"}' }); else await route.fallback(); });
  await page.goto('/scroll');
  await expect(page.locator('.feed-error')).toContainText('Could not load articles.');
  fail = false;
  await page.getByRole('button', { name: 'Try again' }).click();
  await expect(page.getByRole('heading', { name: 'Bioluminescence', exact: true })).toBeVisible({ timeout: 30000 });
});
test('invalid inputs and cross-origin paid requests are rejected', async ({ request }) => {
  expect((await request.get('/api/wikipedia?offset=-1')).status()).toBe(400);
  expect((await request.get('/api/wikidata?id=bad')).status()).toBe(400);
  expect((await request.post('/api/gemini', { data: { title: 'Bioluminescence' } })).status()).toBe(429);
});
