import type {Language} from './languages';
const arabic={
  'Pull down to refresh':'اسحب لأسفل لتحديث الموجز','Release to refresh':'اترك لتحديث الموجز',
  'Cached articles warning':'ويكيبيديا مشغولة. نعرض مقالات جرى تحميلها مؤخرًا حتى تتاح الخدمة مجددًا.',
  'Scroll':'تصفح','Explore':'استكشف','Library':'المكتبة','Stats':'الإحصاءات','Settings':'الإعدادات','Main navigation':'التنقل الرئيسي','Scrollipedia home':'الرئيسية — Scrollipedia',
  'Wikipedia, one article at a time':'ويكيبيديا، مقالة واحدة في كل مرة','by':'بواسطة','Wikipedia discovery feed':'موجز اكتشاف ويكيبيديا','Loading articles…':'جارٍ تحميل المقالات…','Could not load articles.':'تعذر تحميل المقالات.','Could not load articles from Wikipedia.':'تعذر تحميل المقالات من ويكيبيديا.','Could not load topics.':'تعذر تحميل المواضيع.','Try again':'حاول مرة أخرى','Try again in {seconds}s':'حاول بعد {seconds} ثوانٍ','Wikipedia is temporarily limiting requests.':'تحد ويكيبيديا من الطلبات مؤقتًا.',
  'Post options for {title}':'خيارات المنشور: {title}','Not interested':'غير مهتم','Post hidden. We’ll show fewer topics like this.':'تم إخفاء المنشور. سنعرض مواضيع مشابهة أقل.','Undo':'تراجع','Explore topic':'استكشف الموضوع','Save':'احفظ','Saved':'محفوظ','Enlarge image of {title}':'تكبير صورة {title}','Close image':'إغلاق الصورة','Image unavailable':'الصورة غير متاحة',
  'Play narration':'تشغيل القراءة الصوتية','Pause narration':'إيقاف القراءة الصوتية مؤقتًا','Narration is not configured':'القراءة الصوتية غير مفعلة','Narration is not configured for this app.':'القراءة الصوتية غير مفعلة لهذا التطبيق.','Listen to this topic':'استمع إلى هذا الموضوع','Audio unavailable':'الصوت غير متاح','Narration could not be played. Please try again.':'تعذر تشغيل القراءة الصوتية. حاول مرة أخرى.',
  'Your saved discoveries':'اكتشافاتك المحفوظة','Saved topics':'المواضيع المحفوظة','Saved paths':'المسارات المحفوظة','No saved topics yet':'لا توجد مواضيع محفوظة بعد','Bookmark a topic from Scroll to keep it here.':'احفظ موضوعًا من الموجز ليظهر هنا.','Explore topics':'استكشف المواضيع','Loading your library…':'جارٍ تحميل مكتبتك…','Unsave {title}':'إلغاء حفظ {title}','Reopen {count}-topic path':'فتح مسار من {count} مواضيع','Delete path starting at {title}':'حذف المسار الذي يبدأ بـ{title}','{count} topics':'{count} مواضيع','{count} topic':'موضوع واحد','to {title}':'إلى {title}','Wikipedia content · CC BY-SA 4.0':'محتوى ويكيبيديا · CC BY-SA 4.0',
  'Your learning, at a glance':'لمحة عن تعلمك','Loading your stats…':'جارٍ تحميل إحصاءاتك…','Learning stats':'إحصاءات التعلم','Recently explored':'استُكشفت مؤخرًا','Topics in paths':'المواضيع في المسارات','Longest path':'أطول مسار','On this device':'على هذا الجهاز','This session · storage is off':'هذه الجلسة · التخزين غير مفعّل','View library':'عرض المكتبة','Latest {count}':'آخر {count}','Your next rabbit hole starts here.':'رحلتك المعرفية التالية تبدأ هنا.','About these stats':'عن هذه الإحصاءات','Stats explanation':'تحسب المواضيع المستكشفة آخر 12 موضوعًا مختلفًا. تعكس إحصاءات المسارات مساراتك المحفوظة، ويُقاس أطول مسار بعدد المواضيع.','Your activity is stored on this device.':'يُحفظ نشاطك على هذا الجهاز.','Storage is off, so activity lasts for this session.':'التخزين غير مفعّل، لذا يستمر النشاط خلال هذه الجلسة فقط.',
  'Close settings':'إغلاق الإعدادات','Store data':'حفظ البيانات','Storage description':'احفظ مكتبتك والمواضيع المستكشفة بين الزيارات. يؤدي إيقاف التخزين إلى حذف بيانات المكتبة المخزنة، وتبقى المحفوظات متاحة خلال الجلسة. تُحفظ تفضيلات العرض دائمًا.','Language':'اللغة','Language description':'لغة الواجهة والمقالات والموجز وخريطة المعرفة.','Open links in English Wikipedia':'فتح الروابط في ويكيبيديا الإنجليزية','English links description':'تستخدم المقالات الكاملة والخرائط ويكيبيديا الإنجليزية. يستخدم الموجز مقدمات ويكيبيديا المبسطة حيث تتوفر، مع تبسيط تلقائي بواسطة Gemini. أوقف هذا الخيار لتفضيل روابط ويكيبيديا المبسطة.','Feed interests':'اهتمامات الموجز','Feed interests description':'يرتب Gemini المنشورات ويبسطها تلقائيًا. تُرسل اهتماماتك وعناوين بعض المواضيع المحفوظة والمستكشفة والمخفية ونصوص المقالات إلى Gemini عبر خادمنا.','Choose interests':'اختر اهتماماتك','Theme':'المظهر','Auto':'تلقائي','Light':'فاتح','Dark':'داكن','AMOLED':'AMOLED','About Scrollipedia':'عن Scrollipedia','About app':'تعلّم ممتع عبر ويكيبيديا. استكشف المواضيع المرتبطة واحفظ اكتشافاتك. يجمع الموجز بين مواضيع جديدة واهتماماتك والمواضيع المحفوظة والمستكشفة. يرتب Gemini مقالات ويكيبيديا الحقيقية ويبسط مقدماتها تلقائيًا.','About sources':'تأتي نصوص المقالات من ويكيبيديا بترخيص CC BY-SA 4.0. تستخدم القراءة الصوتية ElevenLabs. إذا كانت المزامنة السحابية مفعّلة، تُزامن مكتبتك مع الحساب المجهول لهذا المتصفح.','Reset discovery':'إعادة ضبط الاكتشاف','Reset description':'امسح الاهتمامات والمواضيع المستكشفة والمخفية وابدأ موجزًا جديدًا. تبقى مواضيعك ومساراتك المحفوظة في المكتبة لتوجيه التوصيات.','Delete all data':'حذف جميع البيانات','Confirm deletion':'تأكيد الحذف','Delete description':'هل تريد حذف المواضيع والمسارات والمستكشفات والإعدادات من هذا المتصفح والمكتبة السحابية المتصلة؟','Cancel':'إلغاء','Confirm delete':'تأكيد الحذف','Deleting…':'جارٍ الحذف…',
  'Addictive learning':'تعلّم لا يُقاوَم','Created by':'أنشأه','Intro description':'Scrollipedia موجز لا ينتهي من قراءات ويكيبيديا القصيرة. عندما تجد ما يثير اهتمامك، اضغط «استكشف الموضوع» لتبني خريطة من الأفكار المرتبطة.','Intro sources':'تأتي المنشورات من ويكيبيديا بلغتك المختارة. يستخدم الموجز الإنجليزي ويكيبيديا المبسطة حيث يتوفر مقال مطابق. يخصص Gemini موجزك ويبسط النصوص باستخدام اهتماماتك والمواضيع المحفوظة والمستكشفة.','Intro privacy':'تُحفظ مكتبتك على هذا الجهاز ما لم تُفعّل المزامنة السحابية. تُرسل اهتماماتك وعناوين بعض المواضيع المحفوظة والمستكشفة والمخفية إلى خادمنا للعثور على مقالات مناسبة. تُرسل هذه العناوين والنصوص أيضًا إلى Gemini. يحتاج Scrollipedia إلى اتصال بالإنترنت.','Source code on':'الشيفرة المصدرية على','Pick a few interests to get started':'اختر بعض الاهتمامات للبدء','(optional)':'(اختياري)','Or add your own':'أو أضف اهتمامك الخاص','Custom interest':'اهتمام مخصص','Black holes, Estonia, ancient Rome…':'ثقوب سوداء، إستونيا، روما القديمة…','Add interest':'إضافة اهتمام','Remove interest {title}':'إزالة اهتمام {title}','Some topics may be NSFW.':'قد تكون بعض المواضيع غير مناسبة للجميع.','NSFW description':'قد تتضمن المقالات والصور محتوى جنسيًا أو صادمًا أو مخصصًا للبالغين. تابع فقط إذا كنت بالغًا.','Update my feed':'تحديث موجزي','I’m an adult, continue':'أنا بالغ، تابع',
  'Nature':'الطبيعة','Science':'العلوم','Animals':'الحيوانات','History':'التاريخ','Places':'الأماكن','Culture':'الثقافة','Art':'الفن','Mathematics':'الرياضيات','Games':'الألعاب','Technology':'التقنية','Music':'الموسيقى','Space':'الفضاء',
  'Could not load this topic.':'تعذر تحميل هذا الموضوع.','Retry':'إعادة المحاولة','Retry connections':'إعادة تحميل الروابط','Loading article':'جارٍ تحميل المقالة','Opening {title}…':'جارٍ فتح {title}…','Drawing connections…':'جارٍ رسم الروابط…','Save topic':'احفظ الموضوع','Open article':'افتح المقالة','Hide article':'أخفِ المقالة','Exploration path':'مسار الاستكشاف','Save path':'احفظ المسار','Path saved':'المسار محفوظ','Article':'المقالة','Close article panel':'إغلاق لوحة المقالة','Article sections':'أقسام المقالة','Read the full article on Wikipedia':'اقرأ المقالة كاملة على ويكيبيديا','Connections organized with Gemini.':'روابط مرتبة بواسطة Gemini.','Connections from Wikipedia & Wikidata.':'روابط من ويكيبيديا وويكي بيانات.','Related topics':'مواضيع مرتبطة','No related topics were available. Try another article from Scroll.':'لا تتوفر مواضيع مرتبطة. جرّب مقالة أخرى من الموجز.','Back to Scroll':'العودة إلى الموجز','Overview':'نظرة عامة',
  'Explore connections for {title}':'استكشف روابط {title}','Double tap description':'انقر مرتين لاستكشاف هذا الموضوع. باستخدام لوحة المفاتيح، اضغط Enter أو المسافة.','Loading':'جارٍ التحميل','Explored':'مستكشف','Double tap':'انقر مرتين','Expand':'وسّع','Expanding knowledge map':'خريطة معرفة متوسعة','Fullscreen mind map':'خريطة المعرفة بملء الشاشة','Mind map · {count} topics':'خريطة المعرفة · {count} مواضيع','Phone map hint':'انقر مرتين على دائرة لتوسيع فرع. اسحب لتحريك الخريطة.','Desktop map hint':'انقر على دائرة لتوسيع فرع. اسحب لتحريك الخريطة.','Close fullscreen mind map':'إغلاق خريطة ملء الشاشة','Map controls':'أدوات الخريطة','Zoom out':'تصغير','Zoom in':'تكبير','Focus selected topic':'التركيز على الموضوع المحدد','Show entire map':'عرض الخريطة كاملة','Fullscreen':'ملء الشاشة','Exit fullscreen':'الخروج من ملء الشاشة','Exit':'خروج','Opening connections for {title}…':'جارٍ فتح روابط {title}…','No new connections available':'لا تتوفر روابط جديدة','Double tap another topic to keep exploring':'انقر مرتين على موضوع آخر لمتابعة الاستكشاف','Click another topic to keep exploring':'انقر على موضوع آخر لمتابعة الاستكشاف',
  'Your library':'مكتبتك','Save a topic to find it here later.':'احفظ موضوعًا لتجده هنا لاحقًا.','Open Library':'افتح المكتبة','Articles from Wikipedia.':'مقالات من ويكيبيديا.','Text licensed under':'النصوص بترخيص',
  'Wiki busy':'ويكيبيديا مشغولة مؤقتًا. حاول مرة أخرى قريبًا.','Connections unavailable':'تعذر تحديث روابط هذا الموضوع. لا تزال الخريطة متاحة؛ أعد تحميل الروابط.','Article language unavailable':'لا يوجد مقال مطابق لهذا الموضوع في اللغة المختارة. جرّب موضوعًا آخر أو غيّر اللغة.','Gemini unavailable':'Gemini غير متاح حاليًا. نعرض قراءات قصيرة من ويكيبيديا وفق اهتماماتك.','AI break':'تستريح التوصيات الذكية قليلًا. نعرض قراءات قصيرة من ويكيبيديا.',
} as const;
export type Message=keyof typeof arabic;
const englishOverrides:Partial<Record<Message,string>>={
  'Cached articles warning':'Wikipedia is busy. Showing recently fetched articles while it recovers.',
  'Stats explanation':'Recently explored counts your latest 12 distinct topics. Path stats reflect your saved paths; longest path is measured in topics.',
  'Storage description':'Save your library and recent explorations between visits. Turning this off removes stored library data; saves remain available for this session. Display preferences are still remembered.',
  'Language description':'The language of the interface, feed, articles, and mind map.',
  'English links description':'Full articles and mind maps use English Wikipedia. Feed posts use Simple Wikipedia introductions where available, with automatic Gemini simplification. Turn this off to prefer matching Simple Wikipedia links.',
  'Feed interests description':'Gemini automatically ranks posts and makes them easier to read. Your interests, a few saved, explored and hidden topic titles, and article text are sent through our server to Gemini.',
  'About app':'Addictive learning through Wikipedia. Explore connected topics and save your discoveries. The feed mixes fresh discoveries with your chosen interests, saved topics, and recent explorations. Gemini automatically ranks real Wikipedia candidates and simplifies their introductions.',
  'About sources':'Article text comes from Wikipedia under CC BY-SA 4.0. Narration uses ElevenLabs. If cloud sync is configured, stored library data also syncs to your browser’s anonymous account.',
  'Reset description':'Clear chosen interests, recent explorations, and hidden topics, then start a fresh feed. Saved topics and paths stay in your library and can still guide recommendations.',
  'Delete description':'Delete saved topics, paths, recent explorations, and settings from this browser and its connected cloud library?',
  'Intro description':'Scrollipedia is an endless feed of short Wikipedia reads. Find something interesting, tap Explore topic, and grow a mind map of connected ideas.',
  'Intro sources':'Posts come from Wikipedia in your selected language. English posts use Simple Wikipedia wording where a matching article exists. Gemini automatically tunes your feed and simplifies posts using your chosen interests, saved topics, and recent explorations.',
  'Intro privacy':'Your library is stored on this device unless cloud sync is configured. Your chosen interests and a few saved, explored or hidden topic titles go to our server to find relevant articles. Those titles and source text also go to Gemini to personalize your feed. Scrollipedia needs an internet connection.',
  'NSFW description':'Articles and images can contain sexual, graphic, or other mature content. Continue only if you’re an adult.',
  'Double tap description':'Double tap to explore this topic. Keyboard users can press Enter or Space.',
  'Phone map hint':'Double tap a circle to grow a branch. Drag to move around.',
  'Desktop map hint':'Click a circle to grow a branch. Drag to move around.',
  'Wiki busy':'Wikipedia is temporarily busy. Please retry shortly.',
  'Connections unavailable':'Wikipedia could not expand this topic. Your map is still here; retry the connections.',
  'Article language unavailable':'This topic has no matching article in the selected language. Try another topic or change language.',
  'Gemini unavailable':'Gemini is unavailable. Showing short Wikipedia reads with your selected interests.',
  'AI break':'AI recommendations are taking a break. Showing short Wikipedia reads.',
};
const english=Object.fromEntries(Object.keys(arabic).map(key=>[key,englishOverrides[key as Message] || key])) as Record<Message,string>;
export const MESSAGES:Record<Language,Record<Message,string>>={en:english,ar:arabic};
export function translate(language:Language,message:Message,values:Record<string,string|number>={}){
  return MESSAGES[language][message].replace(/\{(\w+)\}/g,(match,key)=>values[key]===undefined ? match : String(values[key]));
}
